### ISSUE TITLE
[Heads up] Proposing to share the tagging scheme between Joplin notes and Nextcloud-maps tags

### ISSUE THREAD

**Issue by daniel-callejas-sevilla** [laurent22/joplin-nextcloud#1]
I made a suggestion in nextcloud-maps to support a tagging scheme for features on a map.

As part of that idea, I guess it would be great if Joplin notes with geo coordinates could show up naturally in nextcloud-maps, and also the other way around, that Joplin notes could be created with a geo location by clicking on the map and selecting "new Joplin note here".

I fleshed out a bit my thinking here: https://github.com/nextcloud/maps/issues/181#issuecomment-567594166

**Comment by laurent22** [comment]
I think the Maps app is too young to do this kind of integration. Even later, I doubt anyone will be able to do it.
