### ISSUE TITLE
Add support of Nextcloud 18?

### ISSUE THREAD

**Issue by LudovicRousseau** [laurent22/joplin-nextcloud#11]
I have Nextcloud 18.0.4 and I can't install this applet. It only support Nextcloud <= 17.
https://apps.nextcloud.com/apps/joplin

When I try to install I get:
```
Cette application ne peut être installée à cause de ces dépendances non satisfaites :

    Server version 17 or lower is required. 
```

Any plan to support Nextcloud 18?

**Comment by marsender** [comment]
Hi, same problem for me !!

**Comment by rarecoil** [comment]
Duplicate of #6.

**Comment by LudovicRousseau** [comment]
Closing since this is a duplicate.
I should have checked better.
