### ISSUE TITLE
How to use this app

### ISSUE THREAD

**Issue by xianx** [laurent22/joplin-nextcloud#3]
We have installed this app on our Nextcloud instance. Now what to do?

**Comment by Githopp192** [comment]
check --> https://joplinapp.org/
Create a Directory with the Name : Joplin (you can do this anywhere on your Cloud Directory(ies))

Then for example enter the Nextcloud WebDAV-URL (https://<your-cloud-domain>/remote.php/webdav/<your-path-to-the-Joplin-Directory)

**Comment by laurent22** [comment]
And to install the Nextcloud app, search for "Joplin" in the Apps tab in Nextcloud.
